In [15]:
import biom
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

In [7]:
pca = PCA(n_components=100, whiten=True)

### dnabert2_16s_embedding

In [2]:
dnabert2_embed = pd.read_csv("dnabert2_16s_embedding.txt", sep=" ", header=None, index_col=0)

In [3]:
dnabert2_embed.head()

,1,2,3,4,5,6,7,8,9,10,...,759,760,761,762,763,764,765,766,767,768
0,,,,,,,,,,,,,,,,,,,,,
AB002518.1.1416,-0.064145,0.115335,0.040034,-0.067129,-0.082495,-0.072862,-0.097545,-0.128318,-0.013788,0.023373,...,0.020889,-0.047142,-0.093073,0.025427,-0.030634,-0.040504,-0.007037,0.119860,0.131925,0.135318
HL281973.2.1492,-0.073305,0.098124,0.045979,-0.111096,-0.088344,-0.087999,-0.080791,-0.137830,-0.001208,0.044691,...,0.041326,-0.040846,-0.045639,0.002448,-0.026272,-0.063820,0.011493,0.106039,0.111224,0.109531
HL281785.3.1301,-0.035501,0.097548,0.025978,-0.087182,-0.085571,-0.050925,-0.078550,-0.141289,0.007320,0.023146,...,0.032231,-0.020053,-0.066177,0.009753,-0.021312,-0.040064,0.020265,0.118609,0.099815,0.100710
FW576170.1.1394,-0.025100,0.123918,0.072956,-0.080942,-0.101599,-0.037441,-0.065069,-0.123038,-0.017098,0.051157,...,0.070861,-0.084003,-0.099554,0.032349,-0.038336,-0.006010,0.032098,0.107472,0.135171,0.105291
ET632854.1.1312,-0.073271,0.096796,0.049364,-0.088663,-0.106303,-0.081122,-0.070980,-0.118163,-0.005693,0.011825,...,0.025351,-0.054640,-0.073039,0.023438,0.008383,-0.061495,0.022913,0.122923,0.120877,0.061913

In [8]:
dnabert2_embed_reduced = pca.fit_transform(dnabert2_embed.values)

In [10]:
dnabert2_embed_reduced = pd.DataFrame(data=dnabert2_embed_reduced)
dnabert2_embed_reduced.index = dnabert2_embed.index.values

In [12]:
dnabert2_embed_reduced.to_csv("dnabert2_16s_embedding_reduced_100.txt", header=None, sep=' ')

### pretraining data reduction

In [24]:
pretain_df = biom.load_table("gut_pretraining.biom").norm(axis='sample', inplace=False)
pretain_df = pretain_df.to_dataframe()

In [25]:
pretain_df.head()

,10532.00954e18.1dcf.40fc.a52e.255f5cda6f9c,10532.00cdbb86.acbd.429c.abe3.12f19990314a,10532.00e6b118.fb6e.4022.96d1.62e553d9b40c,10532.0129210b.a355.4608.8aac.7e6d637c0b5c,10532.0476f5aa.a4f4.4835.ada1.4e72fb601e0a,10532.049a1207.554b.43e8.9548.1b0fb0f8cd2b,10532.04ea008a.d444.4833.988c.a2a3f5d4ad23,10532.04fd9a21.4876.4619.b4e7.6f6a2473bb98,10532.05ddd9c2.3f7f.4b2a.8432.06f416424741,10532.06104fa3.3f90.4a7a.944c.511c32501925,...,SRS9736993,SRS9736994,SRS9736995,SRS9736996,SRS9736997,SRS9736998,SRS9736999,SRS9737000,SRS9737001,SRS9737002
AAAA02020714.1.1202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAFJ01000001.39328.40836,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAQK01001555.694.2198,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAQK01003909.1492.2988,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AATC01000018.2.1513,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
pretain_df_reduced = pca.fit_transform(pretain_df.values)

In [27]:
pretain_df_reduced = pd.DataFrame(data=pretain_df_reduced)
pretain_df_reduced.index = pretain_df.index.values
pretain_df_reduced.to_csv("pretain_df_reduced_PCA_100.txt", header=None, sep=' ')